name: my_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib
  - numpy
  - pillow
  - pyyaml
  - requests
  - scipy
  - tqdm
  - protobuf<4.21.5
  - pandas
  - seaborn
  - ipython
  - psutil
  - thop
  - streamlit
  - pymupdf
  - pip:
      - opencv-python-headless==4.10.0.84
      - torch==2.3.0
      - torchvision==0.18.0
      - torchaudio
      - rapidocr-onnxruntime
      - onnxruntime==1.15.0
